export const LOGIN_REQUEST = "LOGIN_REQUEST" 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_USER_REQUEST = "USER_REQUEST"
export const REGISTER_USER_SUCCESS = "USER_SUCCESS"
export const REGISTER_USER_FAIL = "USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
